Map<String, List<String>> lines = {
  "Orange": [
    "qzdaGbn`qLiAs@oDwBOKOIm@e@MKiBiAsA_A}CkBwA_A_CsAwCaBeAo@oFwCIEgDiBw@i@i@[}@i@_DeBeAk@QK??a@UYOyCaBwDgB{Ai@_DgA??qA]iBm@eA[wDaASGiA_@uB{@e@UKE??WMmAk@wAu@w@c@iCcBoA}@gDqCwCcC}AiAmA_AwA}@QKg@]SMMG??wAs@cHsCg@MICuEqA[Im@OqAa@_A[}@Uo@Sq@Yg@U]S}@_@e@Sa@Wo@YcAo@oA}@eE_D}@u@????a@]OKo@o@_BiBOOgEoFOSkL{NSUuCyD??SWc@i@qCsDgAuAkNaRoDyEc@m@c@o@]g@??s@eAmDoEsBcCo@y@KIyAmB_@g@oHmJcB_C}AyBw@eAU_@Sc@EMKc@?A??Kg@K_BGmAAkAAcBAu@?_GAiCBwG@qFBcAN{C@g@C[Ke@aHsROQyAU??}@OyBwB{@aASMYK}B_@eDa@UC??y@Go@Ci@Ak@OWKu@q@c@g@iDcDiAuAw@u@AA??sA}AcBsBwAwBaEmDWOOAwC?U???{GCmMf@s@Ha@R??c@Xi@d@cCtCuHlG??QLea@n_@ABqGlKyCjGe@bBCD??yAlEs@nBWv@sB~DmAnB{A|BiBnBmB`B{JdI{Az@c@LID]Ls@Pa@F[Bo@@uFBaDJw@A[AS?qBE??yAEgACcC?W@aA?e@AoA@UA_@@eB@uA@oBHeBBqED{AAeC@eCFmER}@D??gCHaEBuOA}CAoCAgACeBAmCCgA?gACyDGqCEg@CMAgEGo@E??g@CY?W?aB?Q?}CAqB?qQK_GGwABgB?_IGsHGqFEgB?kCDeB@c@?gFEgBMwCWoAMaEs@OEcAWqA]iDcAgF_BgHwBICqBo@[I??qBm@YKyAa@iA]{@[mGkBqIcCiA]OEMEuDiAkBe@mAUeAO_Ee@QAQAUCYCsC[qBQ"
  ],
  "Red": [
    //Alewife - Ashmont
    "}nwaG~|eqLGyNIqAAc@S_CAEWu@g@}@u@k@u@Wu@OMGIMISQkAOcAGw@SoDFkCf@sUXcJJuERwHPkENqCJmB^mDn@}D??D[TeANy@\\iAt@qB`AwBl@cAl@m@b@Yn@QrBEtCKxQ_ApMT??R?`m@hD`Np@jAF|@C`B_@hBi@n@s@d@gA`@}@Z_@RMZIl@@fBFlB\\tAP??~@L^?HCLKJWJ_@vC{NDGLQvG}HdCiD`@e@Xc@b@oAjEcPrBeGfAsCvMqVl@sA??jByD`DoGd@cAj@cBJkAHqBNiGXeHVmJr@kR~@q^HsB@U??NgDr@gJTcH`@aMFyCF}AL}DN}GL}CXkILaD@QFmA@[??DaAFiBDu@BkA@UB]Fc@Jo@BGJ_@Lc@\\}@vJ_OrCyDj@iAb@_AvBuF`@gA`@aAv@qBVo@Xu@??bDgI??Tm@~IsQj@cAr@wBp@kBj@kB??HWtDcN`@g@POl@UhASh@Eb@?t@FXHl@Px@b@he@h[pCC??bnAm@h@T??xF|BpBp@^PLBXAz@Yl@]l@e@|B}CT[p@iA|A}BZi@zDuF\\c@n@s@VObAw@^Sl@Yj@U\\O|@WdAUxAQRCt@E??xAGrBQZAhAGlAEv@Et@E~@AdAAbCGpCA|BEjCMr@?nBDvANlARdBb@nDbA~@XnBp@\\JRH??|Al@`AZbA^jA^lA\\h@P|@TxAZ|@J~@LN?fBXxHhApDt@b@JXFtAVhALx@FbADtAC`B?z@BHBH@|@f@RN^^T\\h@hANb@HZH`@H^LpADlA@dD@jD@x@@b@Bp@HdAFd@Ll@F^??n@rDBRl@vD^pATp@Rb@b@z@\\l@`@j@p@t@j@h@n@h@n@`@hAh@n@\\t@PzANpAApBGtE}@xBa@??xB_@nOmB`OgBb@IrC[p@MbEmARCV@d@LH?tDyAXM",
    //Alewife - Braintree
    "iyr`GzmjpLWAgAGoBQoCMo@EwBSaCKgMeAs@EcDUsEa@wAOqAIg@EeCSqA?[Bs@Ds@H{@JcB\\q@Nw@TiA^mAh@mEvCIFA@MHaGlDqAv@{BlAeHbEg@XULOJWLSJiAr@KFKF[PoBfA{Ar@qD`BmBr@iAXaAVy@P}@Lq@HeAH{@?cAEq@Gk@CSCc@G??qAO}BYMAuAQw@KiBOwBYoCe@mPoCkHmA}@OWCWE_@GkIwA{AWQCMAUEyBa@cGy@oC[_BSuAMiAE{@Bm@FcAPODMDE@YJQDYHq@XeAh@q@\\yBdAi@T??u@\\m@ZmBlAgCjA{@h@w@l@MJKH[Zw@|@wLzMSTQR[XoE~E]`@sDtDoEzEe@d@sAvAsD~DmPxQsF~F}AtA]ZOLOLm@`@IF??yAxAWXkCzCeAtA{HfJiIzIcLzLuC`D}F`G??{@z@uBxB{@`AkCfCgA`Ac@Xw@`@i@Vy@XiAZwDdAqA`@o@PiAj@gAr@aAt@wAnAUV}@fAKJKNEDMNmAvA}BjC_EbFyDnEgDzDgAfAeBnB_F|FIHIJw@~@aAfAcAhAcDrDSTSTg@n@a@b@iL`NmEhFiCxCqLjNcDpD}DvE}HtIgAz@oAz@IDgAh@_A`@_ARy@LkBHy@@wAIuAOqBa@YEsWgE{D}@yCw@}IoCeDcAgF_BkB_@_AK}BEyHXeE@{@@sEJkCF]Bg@@}AFM@a@D_AN??]FSDUBm@FqCd@}@VgAd@eAr@m@f@g@j@{@hAoAhBkBdD[h@}A|Bq@hAUZ}B|Cm@d@m@\\{@XY@MC_@QqBq@{F_C??g@ScnAl@??qCBie@i[y@c@m@QYIu@Gc@?i@DiARm@TQNa@f@uDbNIX??k@hBq@jBs@vBk@bA_JrQUj@??aDfI??[v@Wn@w@pBa@`Aa@fAwBtFc@~@k@hAsCxDwJ~N]|@Mb@K^CFKn@Gb@C\\ATCjAEt@GhBEbA??AXGlAAPM`DYjIM|CO|GM|DG|AGxCa@`MUbHs@fJOfD??ATIrB_Ap^s@jRWlJYdHOhGIpBKjAk@bBe@bAaDnGkBzD??m@pAwMpVgArCsBdGkEbPc@nAYb@a@d@eChDwG|HMPEFwCzNK^KVMJIB_@?iAO??kAOmB]gBGm@A[HSL[^a@|@e@fAo@r@iBh@aB^}@BkAGaNq@am@iDQ???sMUyQ~@uCJsBDo@Pc@Xm@l@m@bAaAvBu@pB]hAOx@UdAKr@??i@dD_@lDKlBOpCQjESvHKtEYbJg@rUGjCRnDFv@NbAPjAHRHLLFt@Nt@Vt@j@f@|@Vt@@DR~B@b@HpAFxN",
    // Mattapan
    "_k~`G|c|pL??YeDCWCIKSKWEm@E{@Cw@C{A?w@Bm@Du@^_DPmADU??Fi@L{@LoABs@@k@?s@Ai@E{@MiAQkAUuAmBcMMu@??AG[mBg@cD_@_C[wBy@kFQkA_@{BWeBKy@Iq@MaBQ}CO{CG{@???CCSASGoA]}FEoACkAAqCAkHCoA@[?Y?M???e@Ao@?MG{@UwBYsAWgAOm@Oq@_@gAEOEKg@eAoA_CaA_B_A_B??AAo@iAaBmCkAqB_AcB_A_Bs@kA]c@OO[SSOUMUKg@OQC_@Gm@Ce@@a@Fk@LmBh@IBsG`BWHSJk@P_@Nq@Xe@VGDy@d@C@??C@uC`B_Al@}Az@yAz@wChBaAh@uAp@u@^a@T[RUNg@V"
  ],
  "Blue": [
    "ktpaG|jvpLBo@BOJs@Hq@~@_DJWJUNOJKDA^KXMROfAkAXORIPOJK??FIN_@H]Hk@F_@NqBJcB?G?y@??@kBMoCcB_WQoB???EGe@Ky@_@sAOeAo@_Ose@kc@sNcM??}@u@iDoCwBqCeAqAs@cAaB_C_BmBQWEQEWAWC}NEu@Ke@Kc@Yq@GMCEEIa@k@sDoEGICE}@gAIIKMm@u@??y@aAo@q@a@]uAcAk@]a@c@g@e@c@g@m@_A}@gBa@{@e@y@cAsAwBoCu@_AUYEGWa@Ua@Se@Si@cAwDo@}B[mA??WcAQk@Ke@Mu@Iw@Gw@AwAB}JAgAGy@WqBMy@Om@]iASe@Qa@Sa@[_@}A_CGIKOoLeQcD_FQWMWe@sAEO??wBaJqBmIa@mBQy@I[Oq@g@wB??u@_DOo@GUSaAI_@I[w@eDMq@EQgAeFWeAO[GO[}@Sk@mAkCy@uAc@w@oAgBc@m@SQ??]a@i@g@UUiAy@_BiAoBiAmF{C}A}@mAq@aFyCsC_ByCgBwCcB??MIUMoAs@oAg@aA]cAS}@OgAKM?]AQAc@?sADkFb@mHl@kHl@iBLyIr@_@FsARUBY@uAF??E?[BaBH{@B}@?kA?cAEcAGuC]k@IcBc@eBi@{DaB"
  ],
  "Green-B": [
    "oplaGpwjqLJq@B_@@W@}@KmBGmBAyAAqDJ}K@eEDaBHoAJ{AVcCJw@RkABQ??Z}AZwAVw@`@mAd@kAdAsCn@kBLg@Lk@DYLaBCUESKWA???AASYMQEEm@g@YQg@Sg@Uc@So@_@c@Wc@_@a@_@[_@w@gAaA_BO[??[s@a@kA[sAQ}@Go@G_ACcB@k@BiB?}@E}AEi@C]??Eo@Im@Mo@S_A]eA[y@Wk@u@oA_@e@]a@]]o@g@w@i@eAm@??ECuAy@{@m@uCeBm@[QI[U_B{@yAk@q@Sc@IiCUg@Mu@W??[KUKIGQYUe@Kc@Ii@Ew@?g@@]B]Ha@d@_CBE??t@aDNo@Jo@Dc@@a@?_@Ag@Gi@Gk@Om@_@cAOa@??O_@uA{DcAiCs@qB_@_A}@eCGM??q@iBOk@Gc@Eg@Ai@?m@FyALyB@k@?gAAe@Eq@QsAKe@Om@Uo@c@eAe@_AYi@q@kAg@o@QY??W_@IQAO?Yh@sIX{E`@wGBg@??PiCHmABo@J_C\\mFRiD^cG??\\oFLkC\\yFBW@[Fw@Da@?EHgA\\uFj@uIRiD??JkBn@qKFkA??`@uGT_ERgDJyA??B]JsBVyEViF@aBEqGMqF?G???A?oC@S@MFQt@aAzAkBHOL_@FWBQ@QQuR?kABm@??D{@Bm@b@aJ?SAOGa@{Igg@YcB_@aCMs@??cJog@Ga@??wAqIe@cDScCKcBXaLC_@CMEKEE??CEyA]]Ma@Ui@SOQQGa@QSIgBw@q@UYO]Co@]i@c@W[_@c@[_@{@eAU]??q@{@UYWQa@c@o@u@uB_Cu@q@eEmC[Ua@]"
  ],
  "Green-C": [
    "}wkaGligqL_@uCQcAEYg@kDcAaIGc@??E]Kw@SiB_@wCc@qDQuAEa@Q{A??QwAk@yDg@gD]eC@PGa@??i@iDgAmHUuAIe@EMUu@Mc@AG??Ie@EYGi@KeBEaAAy@@_C?oDA{AAO???YIgBIeBM_BMmA??EY[oBQiAUiAe@sBOi@_@mAI]KWIYa@gBCO]gB??G_@g@_DKw@g@cEcAiGS_AEUCW??Gc@AYEe@[oBSiAc@wBcBaJ]uB??Ki@OaAs@mDo@uDUmAKm@??s@}Da@wBg@oCUmAAK??_AeFYuAUyAMy@{@sEKc@Om@??GQOq@]aBs@cEkFqXgF{ZAS??COAiECuACkB?EQ}B?G???A?oC@S@MFQt@aAzAkBHOL_@FWBQ@QQuR?kABm@??D{@Bm@b@aJ?SAOGa@{Igg@YcB_@aCMs@??cJog@Ga@??wAqIe@cDScCKcBXaLC_@CMEKEE??CEyA]]Ma@Ui@SOQQGa@QSIgBw@q@UYO]Co@]i@c@W[_@c@[_@{@eAU]??q@{@UYWQa@c@o@u@uB_Cu@q@eEmC[Ua@]"
  ],
  "Green-D": [
    "c_laGhn{qLJa@d@yAL[lAuCh@kAPe@z@{BxAsDvBqF~BcGr@iBv@kBJUJYFWp@cB??t@kBh@qAlA{Cb@eATk@To@lC{G~@{B`AiCd@eA~C_IbAmCzEqLr@uA~@cBjAkBhBqCfBsCHOHKr@iA????tAwBr@sAb@_A`@aAZ_Az@wB~@iCXu@p@kBj@yAjCkHpAgDvBaGx@wBfDcJ`AqCtBuFhCcHHQ??j@aBhAqCL]Vq@^iARy@TgAPiAJeABk@DwB?o@E{AG{@Iq@SmAYsAY{@Um@Yo@]q@e@o@a@i@aAeAMQQSCCOQ{AyAwBwBiEqEWSGE??IIo@q@cAcAaAaA{@eAs@_Aa@q@CEEGe@{@{@{BoBeFEIEIgBgEmCsGy@oBq@aBo@}Aa@eAWq@Qi@}@yB[s@[s@wCuHEMIQy@iBk@wAIUKYm@gBY}@??CIUw@o@eCQy@I[EQYqB[gCW}CMyCCcB?eA@oAF{CLgC^mDdAyIPuAd@cEb@kDXuCb@iDVeCFg@Da@hBgPV{Bl@mFt@kG\\aD`@gD|@eIf@gERqBHaBBmA@_C?O?KA[??KaCAGUeCO}@UoAYkA_@wA[_A_AyB_@w@aB}CeC_FoHqNq@kAISGKw@aBqCmFu@}AgFaKwAkCi@aAg@eAa@_Ai@qA_@mAKg@G[Ms@??OeAMeAGu@Eu@E{@?o@G_AG_Ao@_HIw@OsAG_@K]Ms@Iq@Gs@CcAAuA?mBBkA@W?SDmAHy@??@CV}ADQf@uB\\eAfAgCbEsItAiCf@iA~@oBbBqDf@sA\\kANq@Lq@ZoBHeARaDBW@MNuDTaEPyEVyF??D{@B]LuB@U@Y?k@?o@EuAIiAK{@KcBEeAA{@CoBIuE?QGaFAw@Cc@Gm@OaAQaAKi@YaAKUEOIUk@cBu@_CWu@]}@??Wo@c@aAg@_A_@u@e@y@c@q@iAqAmAkAm@g@g@a@UOm@[MIKGiAi@mBaAkBw@_Ag@]OmCcAmA_@gAUmB[iA[e@Ow@USIMEa@Oo@[o@c@??KGm@i@m@m@s@y@g@q@a@m@c@u@wCqFuByDgAqBgCwE_@u@]w@OWEMOYEI??wAeD}@qB_BmDOUSKUGm@My@IQGIIMMgF{ZAS??COAiECuACkB?EQ}B?G???A?oC@S@MFQt@aAzAkBHOL_@FWBQ@QQuR?kABm@??D{@Bm@b@aJ?SAOGa@{Igg@YcB_@aCMs@??cJog@Ga@??wAqIe@cDScCKcBXaLC_@CMEKEE??CEyA]]Ma@Ui@SOQQGa@QSIgBw@q@UYO]Co@]i@c@W[_@c@[_@{@eAU]??q@{@UYWQa@c@o@u@uB_Cu@q@eEmC[Ua@]??KIQQq@o@uE}DUOUAg@@aGRa@H[BSDKD??_@RMHi@b@MPyAbBmIjH??ONuCrCGPCN?RBh@BVJZbB~Ef@|ALl@D`@Bb@ANCN]~@_@`CKr@KbAUtASt@Sp@Un@Uh@Qd@e@jAELwAfDw@~B??ELo@zAeBlEkBnEqA~Cw@jBsBfFO^s@nBuAjBo@`@A@??]VWPONUZ[h@Qj@WjAUfAmEjLCAGDKFIDMFKBOB[@_A@w@Fo@JSLIDGNMTK`@EXEXAZC`@Cz@i@fK{@lQ{AlUMtBKhA}@nHg@`C}AdFCF"
  ],
  "Green-E": [
    "cgjaGbu_qLCCCAOBGDKLIJW`@QX_@d@e@TgA`@aBn@WF??_Cp@wDbA??SH[FEAEEQYQ[Q]Ua@[i@o@oAM]O_@Yu@Ia@GYAGCW??CUAm@?w@Aw@?w@C_AAuC?qA?[Ee@Mq@Oi@]}@OYKS??Yq@a@eAOi@Ss@??EMQi@k@oBEO}AuFSw@m@mCMk@k@mB]eAOi@IU??m@kBm@}B}B}HcB_Gg@iB??WeA_BaFYaAgAyDUaA_@oAq@}Bq@cCIW{AcFg@_BQi@??s@yBYcA]kAQm@Oe@e@aAWe@gA{A_D}Da@g@k@u@??{MiQSY??_@i@yE{GW]_@Yw@[iHiAOCmBf@QGISYaAYcB_@aCMs@??cJog@Ga@??wAqIe@cDScCKcBXaLC_@CMEKEE??CEyA]]Ma@Ui@SOQQGa@QSIgBw@q@UYO]Co@]i@c@W[_@c@[_@{@eAU]??q@{@UYWQa@c@o@u@uB_Cu@q@eEmC[Ua@]??KIQQq@o@uE}DUOUAg@@aGRa@H[BSDKD??_@RMHi@b@MPyAbBmIjH??ONuCrCGPCN?RBh@BVJZbB~Ef@|ALl@D`@Bb@ANCN]~@_@`CKr@KbAUtASt@Sp@Un@Uh@Qd@e@jAELwAfDw@~B??ELo@zAeBlEkBnEqA~Cw@jBsBfFO^s@nBuAjBo@`@A@??]VWPONUZ[h@Qj@WjAUfAmEjLo@~As@v@y@v@YRe@Ra@FQD_A^YRW\\]h@e@`A[z@IZO^MX_@f@{@~@cAdA_A~@wKdKs@z@aArAe@n@wBvB??_DzC{H|HsDfDiAz@iBnAkApAk@p@u@p@qAvAs@~@k@v@eApBcAvBo@dBaBzEw@|Be@rA??IT{@xBk@xAY|@k@vAaA~Ce@rAiCrHyAvDOd@a@`A[l@m@dAo@dA[h@KPs@~@m@l@{@|@s@t@UPq@f@q@`@ED??UL{@l@cAr@{@j@q@d@a@Vg@\\e@Zg@\\KFQNy@h@i@\\a@XMJgBlAs@d@s@h@cAp@m@`@c@Zw@f@m@b@y@h@_@V_An@w@h@o@b@??IDe@Zk@b@o@b@cAn@_Aj@]VSLa@Xg@\\c@Ze@Xg@\\UNg@\\g@^cAr@{@j@_@T{AfAOJsA|@iD`CqCjBkCdBm@`@OLMJSN"
  ],
  "CR-Lowell": [
    "euqaGrkvpLGFq@p@{D|D}A|AUVUZ_@n@_@p@m@z@_@p@g@t@q@fACDGFCDe@t@INGHS^c@`Ae@r@{EtHABCBEH}@vAc@n@sAlBGJMNGJSTs@z@wAhBuD|EoCtDyPbUSVGHUZKPKRIPO\\O^K`@Qv@Kt@M~AAdA@`BLrEF|CFjC@nB?tAGnAKx@Mz@Sv@_@hAm@tAy@`Bi@fA}AxCe@n@eAjA_@^qAnAcGfG}@x@IJKJg@b@wApAWR_BlA]RSPUNwA|AaA`A_A`Ak@t@i@p@{@jAGNEJw@xAg@jA]x@e@vAUf@Sf@}AvEyAxDENGNcAvCaAjC_ApCs@rBGLCJcAvCq@pBGNCHqAjDs@dBo@jAyAfCe@n@YXy@~@eAfAs@n@OLIFKHi@^yA~@uA~@mBrAQJqCnB}DjCaBfAABE@MJ{DlCcEnC[T_@VgHxE_LvHeAr@}AdAuBxA_An@oGhE_EnCe@ZIDMHGD}B|AmBvAiB~AoAtA}AlBeEtFmEvFILKJe@r@eC`DaLbOGHGFuCvDkB`CgDjEe@n@cAtAw@dA_CxCeB|Be@l@kBfCiCjDiB~B[`@??wAjBkO`SwL|OkDnEcCbDGFMPk@v@w@~@y@hAeAnA_AfAgAbAsAdAwA~@iB`AcA`@yAh@uA`@yATgAN{ANaCLqER{ABqAAuAC{@EkAIqAQaAQgAYkA_@gAa@_Ae@c@WWOaBiAaAw@y@w@}@aAsCcDmAqAkAeAw@q@iAw@k@]WOqAq@WM??[Mk@UyBm@yA_@oUqG}F}AgBi@IC_AW_AY??g@OgAYoA]y@SmNyD}@WsA_@kDaAeHoBkHoByC{@_HkBuCy@yA_@cEiAgEkAcBe@uA_@aA[_A]m@YiBy@}Aw@uE{BeFgC{E_C{KkFyCwA_Bs@aA_@w@Ua@K]MmASiBUeAGsAE_@Ai@?W@y@@m@B}BTcDb@ODQB}A`@o@RiAb@kAf@s@^wBnAw@p@o@j@iDdDo@p@k@f@cA`A{B|BsBnBgAbAaBnAsA~@}Av@_Bl@yAd@KBQHkB^iBTs@HsBJs@?{@CsGYm@AoA?_AFq@FcALo@HiAVeAVmBd@cE`AcCj@wFtAIBOBc@Pk@N{Bz@iDnAo@VeC~@_AZUHc@R[Ly@\\uAf@{@\\UHUHyAh@cEtAaElA_Cp@sCz@gEpAgBn@qAh@yAx@eCpAwHdEoAt@_Af@aRvJmE|BaM`HuBfA{Ax@cCvA??QJk@\\_G~CaCrAgDfBsJhF_Aj@cFxDwCjCsK`LIHA@IHoArAkD~DcMnPmDxEMP??ORmHrJyDlFwIjLGFeEtF}BzCuCvDsFpH{K`OwBpCsAbBcB|Bs@x@GFA@???@EDc@d@[XSTMJk@j@{ErDeE|CgDjCoIrGgB`BMLGH}@~@q@|@kCdEiFtIcExGIJkBfDuBbDKNKNW`@sCrEiDpFyEzHsDhGy@vAc@z@oAtCa@jAk@fB{B`Ig@bByAvF}E`QI^}DlN}GjVENGPeAvDsBlHcK|ZqDnK{AjE}@nCGLu@|B{EpNeCpHoJbYiD`KoEvMcBbFGNCH}Oje@gKvZeEfM{DfLiBhF{GfSkH`TCNGV_AtC]tAc@pBe@fCUdBKz@KxAU|CIbBSbGArD@xAD~AFtAHpAPvBhCfTRjBLpAFv@NdDDlC@pAAbBCfACZ?TATEbAKfBK|@Gt@UhBSxASdA_@pBg@nB[hA]dAUn@g@jAoBdE}@xAeBzB_AhAiAlAcA|@w@n@g@^MH{Av@yAr@????gA^aAZoIbCqEnAsBj@oCt@_IxBwF|A}GlBMDqNvD_I~BmAVy@TeEhAoAZQFw@TiCr@_AXqGdBmHrB]Hq@RmAb@w@\\u@ZuC|AmBpAs@h@kAbAaBbBqA|Am@v@ORMR_@j@_@h@w@tAi@`Au@`B}DnJkAvC}@lBi@lA[n@]l@qAvB}ArB}AjByHbKMNIJIJmA`BgDxEkCzDkA~A_BxBq@bAy@tA}AxCyBjEg@`A]n@gAlBu@hAyB`C}DrEiCrCm@j@WTeBxAsClBa@VgAn@aE`CSHgD~A"
  ],
  "CR-Haverhill": [
    "wdadGb`{pLFA`AEbAAX?zGFbDDhB@nBL^HVFn@RHDn@Zz@l@lAdAj@j@dBlBv@fA|@tA??f@v@rBlDxChFd@x@l@hApBfDpDhGxJxPdBxClFhJp@dA`FtItAfCf@x@`BnCfAlBhBvCdCpEJPhAnBp@bAj@r@RVt@x@h@p@r@p@`@^rBnAn@Z~@b@xAf@xB`ARDXJTJNFJD`FzA`C|@nBp@zBz@bAXvGfC|CfApC~@vFlB`C|@vC`AbC|@tA`@bCv@h@R|@\\tCbArDvAr@\\t@d@`BhAtApA|FpGr@x@jBrBzHvI|@`AvCbDnAzA~BhCh@h@jArAhBnBfErE~BlCRTnB|BpBxBzN`P~HxItA~AdBdBf@b@x@n@~Ax@t@ZlBf@lANt@F~BHb@A|@GhCc@tDi@xCi@lBYtDo@pHoAnDg@fDMdBHz@Fp@F|@RfAVl@Rx@Zr@V~@h@jBnARLx@p@t@r@PPp@~@XT`@^b@`@fBbBh@j@`@h@^f@~@|A\\j@j@fA`@z@v@nBXx@Tl@Rp@p@zBDRTjAH^Lj@BL?DJh@DTJn@@H?DBNLj@Jz@RjBHpAF|@Bt@JdBBx@JlCFz@NvDFzBL`DN|CLvCPtDNrDLzCHfCNpF?L??D~@@X@VVtGX|GJtAXlBf@rCLf@FXVz@X~@h@nAh@dADHVb@p@`Ab@f@jAfAx@h@j@\\bAb@x@Vv@R|@Lb@DVDzB@bAC`AOHCj@Ql@S`@S`@UxDqC`LqI|BgB~DuCtDsChDoCvC{BzCwBnDqChF_ExCwBLMzDuCvBaBvAeAfEeD|C_CHINKVSJIZUjDkC|DwCdJcH^W`B{Ar@g@zBwA`@YbB_AnAo@vAu@zA{@RKnCeA|Bu@~@Y~Bg@fBc@zA[bB[d@Kx@Kv@GzAGdACjAA|AFxDXhANvB^xAX|@Rv@PtE~@@???tBf@xAZhAZ|A\\@?pEdA|Dz@xBd@vBf@??lAXJBHB~A^nA\\ZJnAd@vCrAzBvAlG`E|HfFvClBrAz@`G~DvExCn@b@pCjBtH`F|H~E|GtEvGhErMrInCdBlB`ApBbAbFlBxC~@pDx@pDn@rBPdEHdCApBK~C[nI}@fCW????n@Ih@GH?dHs@tD[jEEdGPrDZ~Cf@fARv@T~Ab@fBh@t@P`MpDbBd@tFbBtDdAjDbArBj@vBf@|BZhDZbD^nCTzBVnOvA|ALbD^dAHjRjBnFb@rFn@^B\\BrANpKdAhFd@h@FVB@?^DfDXNBD@ZDpD\\vBPtBVtD\\v@JxAHnJ`A|BRrCZ~Fj@~Hl@tBDpEO|Da@hE{A|DgBpF{DjAaArBeB??tWsTxM}K??l@g@r@k@fGiFbH}FpD}CxE_EtD}C~G}FlHeGfByAlCwBzDgD`G_FvGwFhB}A~O{MnGmFbCoBzG_G|CiCjA_AvCeCx@q@~@y@hEmD^]TQZYXQ`@a@dDmCbBuArAkAlByAzAqAj@g@nAeAJIXUdBsAdCuBXS~AqAf@c@`@[rFsEh@a@fDwCl@k@RUNQdAkAh@o@v@eAjC}DjBuCtBgD`FuHtCoEvD}Fd@u@HKb@u@tCiEvBiDr@cAd@u@lFkIl@}@h@w@tBiDf@_A`@w@Zq@DIDIz@kB^aAb@mA|DqL`@qAlAsDl@eBdBmFd@oADOtCuI??lBwFh@cBPg@b@gApCoI`@oADOz@uCdAkDtEiN^gAdCsHdAcD~AwEZ}@xFsPrAqEL[Nk@JWbBmEhByEBG~AcDhByClBsChHkKBEBEtDoFfBmC|@qA~@qAnA{A`AcAxAuAzBmB`CmBvM}K`BqAhB}APO??tBeB|@w@zHoGnHiGvC}BzCoBbB{@~CoAbAY`@MpBe@nB]lBYxAOxAMnAIjACfDAtA@tA?T?F?H@D?xB@T?zACnAE`AIbBUtAU`ASdBe@bA[zCmAbBs@tF}B`@OfAe@??~BcA|Am@tAm@tAg@dAe@pAa@~@U~@Q|@MnAI|@Ar@Bd@BF@D?J@`ALjARfAVdAT`B`@v@ThARtElA~HlB~HjB`Dx@tCr@^J??v@TrBf@nBd@vD`A~Bj@hFpAdBb@fCh@jBZx@LL@jAHjABdAAr@AbCQp@OzAUzA[~Ae@VG??vCq@fBa@fASxDa@dAGtCIdA?rCB`@@fDLfETn@Bb@B??p@BjCPzP|@jUjAz@F^@tDX~BL|GL`GTzAH~ETnEJlIv@RBNBbD\\|@L|AVvAVnBl@nBl@PFJB~Cx@jDhAjA\\lIfC|DnAjCx@HD??dBf@lEtAdEnA~Br@hFzA~@VXFrEx@xARrF^|DFrAAn@?jAC|F@dKDL?l@K`A?~DBfA@tD@dB?@?pE@dA?|DBhCF`DH^@lK?X?H?L?vA?xF@N?`C@l@@|DLdGLnABvCF|GBjH?bE@lBAt@AbAIbEStAE`AEdCEpF@`AAnAEjACdA@`EIXAfACZAZ?B?F?T?`A?P?F?T?T?|@?~B@lBBzCBrCBlHFj@@hBHbA?N?d@AZG^MFEXG|@OtAc@v@Yz@g@\\UXWt@o@\\a@z@eArVo[l@u@FGLOHKx@kA\\g@\\k@|@sADG@CBCnEeHj@}@pAuBFIFMl@cADIDKRY~AcCh@{@Tc@jAmB\\_@tAoApBqBfAiAHELCNAFAFG",
  ],
  "CR-Fairmount": [
    "qqx`GbgdqLg@sAmA_Dw@y@uA{A][q@w@u@o@aAs@sAw@wDsBiAq@wC_BsAy@qBcAeBeA{Ay@gAo@qDqB_CcB_Au@aAaAcAaA_BuAkAqAgAiAcC}BqDoDGKOMaD}CeE}DoAoAqEmE????KKKKy@}@m@k@q@o@iCyCkBiC{@oA{BiD}@{AqBcDcBoCsA{B}@}A{@cBe@cAq@sA}@wBaDwHs@eBm@sAiC}F}@qB_AoBe@u@s@aAq@w@iAgAOQKKmBmBeG{GkCqC_AgA}@y@mE}Ea@_@{@{@_BcB}BeCcBmBa@i@yA_CyEgIaFeI]_@]c@UYw@_AsBsBw@w@QUMOcEkE_EaE_FgFwB{BqDyDcDgDe@c@eA_A_@Y??s@g@WOIIIGOKwGoEoBwA]U[S{ByA{BcBu@u@iIoJEE}@aAiAiAe@c@}@o@oAw@q@_@EC}@c@kAe@cDy@eBUkAMaBG{AAs@BwAJoCRcEZg@FM@I@kBNeCT}ALyAJO@OByE^cDZe@Fy@HkADgA@{@?iAC}AKk@G{AUmAYuAc@{@_@s@]UKMGiAm@gAq@IEu@o@y@u@s@u@y@cAwAaBcCwCkByB{@gAw@y@aA_A_Au@w@e@}@g@gCgA]McAc@}@_@gAa@wCgA_CaAcA_@eBs@uAi@[KIEOEaBm@eGcCwAi@_Ac@iAa@w@U{A]_BYIA_Eu@[E??gAQmCg@sAQsEy@aAMmGiAeASsB[sAWmAWeAWuAg@_C_AWOKGqAo@sFwCeCuAkFuCiCwA}@i@i@WcB_Aa@S{@g@a@Ua@So@Y}A{@mAm@iBgAmE{BOM}A}@sAw@i@Y_@Oq@MYE{BBeHN}DDoDJgA@aABw@?aABW?c@CS?OGOEk@Oo@OwAg@qAy@iBcAMIGGIEuEoCyD{BgBiAiAq@u@_@i@[k@[sDcBq@YkLaFkAIIC"
  ],
  "CR-Providence": [
    "oynaGn{tpLHBb@NpDvAnIlDhA`@|BhA\\Pd@Vl@`@vBnAZX^f@n@z@Vd@Rd@Pf@P|@D`@Bl@@f@?XAb@Gl@MfAAJGVEb@EZERCNShB]fCUbBIp@ETo@`FEVGVq@`EGd@APIx@G`AKdAEjAS~DItAGbAArFCnE?dA?jC?lD?hA?R@J?\\BlDBn@B^Fx@Bb@Jh@????Jd@DLR`@T^v@dA|AzBlBhCnI|JrArBJJ~E`GbDdEX`@x@jAhAvAtBpCFHhBhCdApAnAvA`AnAFH`DhEt@`AHJRV~BxCd@l@t@~@`@j@bAvALLTXn@v@bIbKt@dAJN`InJVVXXjAbApElDfBdA~B|A|At@LDJDfA\\vBt@b@NbBh@tCr@z@XjBb@ZD~A`@tEbC|BbA|@j@z@j@fDbClA~@lAdAbBtAjA|@x@p@XPJF~AdA^V~@h@pAn@vAt@fAd@xAj@dBl@~EvAt@VJBfDhAxE`BfChAxE|BJDJH`@NzA~@THvIzEvCdBJF~@l@pBjAdBdAHBJFTLLFt@d@~EhCtHlEf@VxBpALHd@Z|@j@TLpCbBv@d@v@f@vBpAr@b@^T`DlBDBRLJFbCxAvHvEz@b@DBjEpBfAb@dDfAt@Vn@L~@VdB\\tC^~CTrCR~HZnHNfEAH?L?jEDpBAfB@nDDdC?hBDhEVL@nAPpDb@J?LBtANzKvAvDd@rFx@hAJ`JhAjDl@rALHBlCXvDf@fDd@f@HxARvCXbDd@fFn@zDj@nFr@nANJ@LBzFr@fEn@p@HbH|@tCd@bDt@zC~@PFLDbA`@??RHnBr@tAf@r@XxDxAbA`@zBx@vAj@n@Tv@XvBz@nEbBl@VrAd@fAd@pAd@JDLDp@TnFtBt@Z~@\\lCfA~CfAdDpAvB|@vDpApBz@bA\\j@TtAf@tAj@xAh@PDJFRFfDlA|Ap@vAj@JDFB~KjEjDpA~@^|@^rAf@nAf@dDjA~D|A`ExAtBz@l@RnDpAvBx@bBp@`Bv@|@Z`A\\dBp@|@^vAf@vCfA|Al@rr@|WzXnKPHLDNFLDLFbDlA^L|Al@lAd@bNdFZNn@Z`HhCtAl@xBt@`E~AbA^vBz@l@V|Aj@tDvAh@PtEhB`DhAfA^`@PRH`A\\h@RlBt@lAf@FBLFhBn@nE|AvAb@pAX~@R`ARzARvBZhCRfBH`BBzCAxFMXATAX?l@CXCV?jHSpCG|AGjNa@zBElCIhCGrK[pGS|JUhK]tDKdIWzA?nCItDG`FKrBIZEd@AtAGfDIJ?H?jCGvBG`CGB???PCVMXS\\WXSVSZ]f@m@h@}@pAoBn@}@fAcBbAyA`CwDbCoDtA_CjDkFbAaBlAkCZw@??Tm@vA_FpBuFvCyGvJaPpEgKf@gAZaA~BkGhBqFzBwFnA}DjAaDr@iBbAqBJOnAcBbAsAjCmCxBuB`DmCpB{AvAy@dDwA|Bs@~Bs@nH_C`JkCvDmAdC}@`DcAtDeA|HeCbAYjBi@|As@nAq@bAw@`Ay@vA{A`AiA~@kA|BsDjByD|@yB`AgDl@yBnCsKdBkHbBkGbBuGp@yCx@qDj@_C~@{D^cAb@eAl@cAx@iAf@o@`AaA"
  ]
};
